import Head from 'next/head'
import Image from 'next/image'
import { request } from "../lib/datocms";
import styles from '../styles/Home.module.css'
import ReactMarkdown from 'react-markdown'

export default function Home({data}) {
  const {
    article:{
      id,
      slug,
      title,
      _createdAt,
      _modelApiKey,
      content,
      featureImage
    }
  } = data

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id={id}>
          <Image src={featureImage.url} width={800} height={400} alt={featureImage.alt} />
          <h2>{title}</h2>
          <p>{`Publish on: ${_createdAt}`}</p>
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const data = await request({
    query: ARTICLE_QUERY
  });
  return {
    props: { data }
  };
}

const ARTICLE_QUERY = `query ArticleQuery {
  article {
    id
    slug
    title
    _createdAt
    _modelApiKey
    content
    featureImage {
      url
      alt
    }
  }
}`;
